"""add google oauth fields to tenant

Revision ID: 11ef9c792c5e
Revises: eca9b115d7bb
Create Date: 2026-05-25 12:00:44.653453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ef9c792c5e'
down_revision: Union[str, Sequence[str], None] = 'eca9b115d7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('tenants', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('google_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('google_account_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('google_location_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'google_location_id')
    op.drop_column('tenants', 'google_account_id')
    op.drop_column('tenants', 'google_token_expiry')
    op.drop_column('tenants', 'google_refresh_token')
    op.drop_column('tenants', 'google_access_token')
    op.alter_column('reviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
